### ISSUE TITLE
svelte is both a dev dep and runtime dep... ?

### ISSUE THREAD

**Issue by elidoran** [sveltejs/svelte-cli#18]
[dev dep](https://github.com/sveltejs/svelte-cli/blob/faa366a2e9b6e7d91b8e145f43db878b78123de2/package.json#L49)
[runtime dep](https://github.com/sveltejs/svelte-cli/blob/faa366a2e9b6e7d91b8e145f43db878b78123de2/package.json#L52)

Should it only be a runtime dep?

**Comment by Rich-Harris** [comment]
It's a dev dep for the purposes of testing... but yeah, it doesn't make a huge amount of sense. I suspect what happened is we needed a more up-to-date version to get some tests to pass, and I did `npm install -D svelte@latest` instead of `npm install -S svelte@latest`.

They'll both be satisfied by the highest version below 2 though, so it shouldn't result in duplicate copies.

**Comment by elidoran** [comment]
I thought so. Figured I'd mention it in case it was escaping notice because I've done it a few times.

Extra babble: I learned `npm update -S` (or -D) is handy to avoid that. Won't add it like install. Only updates what's listed.

Thank you for the quick reply. :)
